### ISSUE TITLE
full system error

### ISSUE THREAD

**Issue by Yongze-zzz** [gem5-gpu/gem5-gpu#2]
Dear authors, there are some problem happened when I run the rodinia backprop benchmarks under full system simulation.
![65a2d772f058cf5902b2b5d8ddcb9a5](https://github.com/gem5-gpu/gem5-gpu/assets/70116723/464d45bc-eda5-414c-a69a-77befb73badd)
It seems like gem5-gpu could not work on my system.Could you provide some advice for me? thank u.

**Comment by powerjg** [comment]
This repository (and simulator) are no longer supported. I suggest using the GPU model in upstream gem5 which implements an AMD architecture. See https://www.gem5.org/documentation/general_docs/gpu_models/vega for details

**Comment by Yongze-zzz** [comment]
Thank you very much ! By the way, could vega support simulate huma on the device such as nvidia tesla t4, a100 and so on？
If possible, when simulating the full system, do the CPU and GPU access memory with the same cacheline size? I would like to know more about VEGA and what documents I can refer to. I would be very grateful and look forward to your reply.
